-- SocSys schema + seed script for Supabase (PostgreSQL)
-- Designed for Supabase SQL Editor and safe re-runs.

-- If you need a full reset in Supabase, run this block manually first:
-- DROP TABLE IF EXISTS public.payment CASCADE;
-- DROP TABLE IF EXISTS public.maintenancebill CASCADE;
-- DROP TABLE IF EXISTS public.complaint CASCADE;
-- DROP TABLE IF EXISTS public.rental CASCADE;
-- DROP TABLE IF EXISTS public.sale CASCADE;
-- DROP TABLE IF EXISTS public.house CASCADE;
-- DROP TABLE IF EXISTS public.tenant CASCADE;
-- DROP TABLE IF EXISTS public.owner CASCADE;

SET search_path = public;

-- Core master tables
CREATE TABLE IF NOT EXISTS public.owner (
  ownerid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  contact VARCHAR(20),
  address VARCHAR(255),
  street VARCHAR(100),
  city VARCHAR(50),
  email VARCHAR(100) UNIQUE NOT NULL,
  password_hash TEXT,
  password_salt TEXT,
  idproof VARCHAR(50) UNIQUE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.tenant (
  tenantid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  contact VARCHAR(20),
  address VARCHAR(255),
  street VARCHAR(100),
  city VARCHAR(50),
  email VARCHAR(100) UNIQUE NOT NULL,
  password_hash TEXT,
  password_salt TEXT,
  idproof VARCHAR(50) UNIQUE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.house (
  houseid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status VARCHAR(50) NOT NULL CHECK (status IN ('Empty', 'Occupied', 'Rented', 'Sold')),
  size VARCHAR(50),
  block VARCHAR(20) NOT NULL,
  address VARCHAR(255) NOT NULL UNIQUE,
  currentownerid_fk INTEGER REFERENCES public.owner(ownerid) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Marketplace and tenancy
CREATE TABLE IF NOT EXISTS public.sale (
  saleid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  houseid_fk INTEGER NOT NULL REFERENCES public.house(houseid) ON DELETE CASCADE,
  buyerid_fk INTEGER NOT NULL REFERENCES public.owner(ownerid) ON DELETE RESTRICT,
  sellerid_fk INTEGER NOT NULL REFERENCES public.owner(ownerid) ON DELETE RESTRICT,
  saledate DATE NOT NULL,
  saleprice DECIMAL(12, 2) NOT NULL CHECK (saleprice >= 0)
);

CREATE TABLE IF NOT EXISTS public.rental (
  rentalid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  houseid_fk INTEGER NOT NULL REFERENCES public.house(houseid) ON DELETE CASCADE,
  tenantid_fk INTEGER NOT NULL REFERENCES public.tenant(tenantid) ON DELETE CASCADE,
  rentamount DECIMAL(10, 2) NOT NULL CHECK (rentamount >= 0),
  startdate DATE NOT NULL,
  enddate DATE,
  CHECK (enddate IS NULL OR enddate >= startdate)
);

-- Billing and complaints
CREATE TABLE IF NOT EXISTS public.maintenancebill (
  billid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  houseid_fk INTEGER NOT NULL REFERENCES public.house(houseid) ON DELETE CASCADE,
  amount DECIMAL(10, 2) NOT NULL CHECK (amount >= 0),
  billdate DATE NOT NULL DEFAULT CURRENT_DATE,
  duedate DATE NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Paid', 'Overdue'))
);

CREATE TABLE IF NOT EXISTS public.payment (
  paymentid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  billid_fk INTEGER NOT NULL REFERENCES public.maintenancebill(billid) ON DELETE CASCADE,
  amountpaid DECIMAL(10, 2) NOT NULL CHECK (amountpaid >= 0),
  datepaid DATE NOT NULL DEFAULT CURRENT_DATE,
  mode VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS public.complaint (
  complaintid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complainant VARCHAR(100) NOT NULL,
  type VARCHAR(60) NOT NULL,
  house VARCHAR(255),
  description TEXT NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'In Progress', 'Resolved', 'Rejected')),
  date DATE NOT NULL DEFAULT CURRENT_DATE
);

-- Auth and user lifecycle tables
CREATE TABLE IF NOT EXISTS public.buyerprofile (
  buyerid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  google_email VARCHAR(120) UNIQUE NOT NULL,
  full_name VARCHAR(120),
  phone VARCHAR(20),
  password_hash TEXT,
  password_salt TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.adminaccount (
  adminid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(120) UNIQUE NOT NULL,
  full_name VARCHAR(120),
  password_hash TEXT NOT NULL,
  password_salt TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.socsysaccount (
  accountid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role VARCHAR(20) NOT NULL CHECK (role IN ('tenant', 'owner', 'admin', 'buyer')),
  linked_email VARCHAR(120) NOT NULL,
  personal_email VARCHAR(180) UNIQUE NOT NULL,
  google_email VARCHAR(120),
  phone VARCHAR(20),
  password_hash TEXT NOT NULL,
  password_salt TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (linked_email, role)
);

CREATE TABLE IF NOT EXISTS public.passwordresetotp (
  otpid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  accountid INTEGER NOT NULL REFERENCES public.socsysaccount(accountid) ON DELETE CASCADE,
  otp_code VARCHAR(10) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  consumed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.owner
  ADD COLUMN IF NOT EXISTS password_hash TEXT,
  ADD COLUMN IF NOT EXISTS password_salt TEXT;

ALTER TABLE public.tenant
  ADD COLUMN IF NOT EXISTS password_hash TEXT,
  ADD COLUMN IF NOT EXISTS password_salt TEXT;

ALTER TABLE public.buyerprofile
  ADD COLUMN IF NOT EXISTS password_hash TEXT,
  ADD COLUMN IF NOT EXISTS password_salt TEXT;

-- Useful indexes for current API queries
CREATE INDEX IF NOT EXISTS idx_house_owner ON public.house(currentownerid_fk);
CREATE INDEX IF NOT EXISTS idx_rental_tenant_start ON public.rental(tenantid_fk, startdate DESC);
CREATE INDEX IF NOT EXISTS idx_rental_house_start ON public.rental(houseid_fk, startdate DESC);
CREATE INDEX IF NOT EXISTS idx_bill_house ON public.maintenancebill(houseid_fk);
CREATE INDEX IF NOT EXISTS idx_payment_bill_date ON public.payment(billid_fk, datepaid DESC);
CREATE INDEX IF NOT EXISTS idx_sale_house ON public.sale(houseid_fk);
CREATE INDEX IF NOT EXISTS idx_buyer_google_email ON public.buyerprofile(google_email);
CREATE INDEX IF NOT EXISTS idx_account_personal_email ON public.socsysaccount(personal_email);
CREATE INDEX IF NOT EXISTS idx_otp_account ON public.passwordresetotp(accountid, expires_at DESC);
CREATE INDEX IF NOT EXISTS idx_admin_email ON public.adminaccount(email);

-- No demo/fake seed data is inserted by this script.
-- Create real owner/tenant/buyer/admin records through app/admin flows.
